### ISSUE TITLE
create logos

### ISSUE THREAD

**Issue by ejh243** [ejh243/MunroeJargonProfiler#4]

**Comment by rgaiacs** [comment]
08de226 has some drafts for badges:

- Complex text ![1](https://cloud.githubusercontent.com/assets/1506457/24425296/9880ab66-13fb-11e7-8857-129a7995b5a6.png)

- ![2](https://cloud.githubusercontent.com/assets/1506457/24425295/987fe3c0-13fb-11e7-9969-3de1937dbdd6.png)

- ![3](https://cloud.githubusercontent.com/assets/1506457/24425298/9882dc56-13fb-11e7-8ef2-801509906d83.png)

- ![4](https://cloud.githubusercontent.com/assets/1506457/24425299/98882bca-13fb-11e7-9f0c-d3d8a30a0b3e.png)

- Simple text ![5](https://cloud.githubusercontent.com/assets/1506457/24425297/9882160e-13fb-11e7-90fe-759eb8b82ced.png)
